load("//haskell:defs.bzl", "default_ghc_flags")

haskell_library(
    name = "lib",
    srcs = glob(["**/*.hs"]),
    compiler_flags = default_ghc_flags,
    visibility = ["//myproject/..."],
    deps = [
        #"//haskell:aeson",
        "//haskell:base",
        #"//haskell:containers",
        "//myproject:pkg-a",
    ],
)
