# THIS FILE IS AUTO-GENERATED -- DO NOT EDIT --
#
# Note: regenerate with `buck2 bxl haskell/toolchain.bxl:libs`

[
  "aeson"
  "attoparsec"
  "base"
  "bytestring"
  "case-insensitive"
  "conduit"
  "conduit-extra"
  "containers"
  "crypton"
  "deepseq"
  "directory"
  "exceptions"
  "hashable"
  "http-client"
  "http-conduit"
  "http-types"
  "ini"
  "lens"
  "memory"
  "mtl"
  "regex-posix"
  "resourcet"
  "retry"
  "scientific"
  "text"
  "time"
  "transformers"
  "unordered-containers"
  "uuid"
  "vector"
  "xml-conduit"
  "xml-types"
]
